name: CI test to build the CCPP-SCM on ubuntu v22.04 using NVidia compilers

on: [push,pull_request,workflow_dispatch]

jobs:

  build_scm:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        fortran-compiler: [nvfortran]
        build-type:       [Release]#, Debug]
        py-version:       [3.7.13]#, 3.9.12]

    # Environmental variables
    env:
      NFHOME:      /home/runner/netcdf-fortran
      NFVERSION:   v4.5.3
      bacio_ROOT:  /home/runner/bacio
      sp_ROOT:     /home/runner/NCEPLIBS-sp
      w3emc_ROOT:  /home/runner/myw3emc
      SCM_ROOT:    /home/runner/work/ccpp-scm/ccpp-scm
      suites:      SCM_RAP
      F90FLAGS:    -O3
      CC:          nvc
      FC:          nvfortran

    # Workflow steps
    steps:

    #######################################################################################
    # Cleanup space
    #######################################################################################
    - name: Check space (pre)
      run: |
        df -h

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false

        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Check space (post)
      run: |
        df -h

    #######################################################################################
    # Initial
    #######################################################################################
    - name: Checkout SCM code (into /home/runner/work/ccpp-scm/)
      uses: actions/checkout@v3

    - name: Initialize submodules
      run: git submodule update --init --recursive

    #######################################################################################
    # Python setup
    #######################################################################################
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{matrix.py-version}}

    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
        df -h

    - name: Install NetCDF Python libraries
      run: |
        conda install --yes -c conda-forge h5py>=3.4 netCDF4 f90nml
        df -h
    - name: Update system packages
      run: |
        sudo apt-get update
        df -h

    #######################################################################################
    # Install Nvidia.
    #######################################################################################
    - name: Cache Nvidia HPC
      id: cache-nvidia
      uses: actions/cache@v3
      with:
        path: /home/runner/hpc_sdk
        key: cache-nvidia-key

    - name: Nvidia setup compilers
      if: steps.cache-nvidia.outputs.cache-hit != 'true'
      env:
        NVCOMPILERS: /home/runner/hpc_sdk
        NVARCH: Linux_x86_64
        NVHPC_SILENT: true
        NVHPC_INSTALL_DIR: /home/runner/hpc_sdk
        NVHPC_INSTALL_TYPE: single
      run: |
        mkdir /home/runner/hpc_sdk && cd /home/runner/hpc_sdk
        wget -q https://developer.download.nvidia.com/hpc-sdk/24.1/nvhpc_2024_241_Linux_x86_64_cuda_12.3.tar.gz
        tar xpzf nvhpc_2024_241_Linux_x86_64_cuda_12.3.tar.gz
        nvhpc_2024_241_Linux_x86_64_cuda_12.3/install
        export PATH=${PATH}:${NVCOMPILERS}/${NVARCH}/24.1/compilers/bin
        echo "The nvfortran installed is:"
        nvfortran --version
        echo "The path to nvfortran is:"
        command -v nvfortran
        echo "Removing tarball"
        rm nvhpc_2024_241_Linux_x86_64_cuda_12.3.tar.gz

    #######################################################################################
    # Install FORTRAN dependencies
    #######################################################################################
    - name: Environment for nvidia compiler.
      run: |
        export CC=nvc
        export FC=nvfortran

#    - name: Cache bacio library v2.4.1
#      id: cache-bacio-fortran
#      uses: actions/cache@v3
#      with:
#        path: /home/runner/bacio
#        key: cache-bacio-fortran-${{matrix.fortran-compiler}}-key

    - name: Install bacio library v2.4.1
#      if: steps.cache-bacio-fortran.outputs.cache-hit != 'true'
      run: |
        git clone --branch v2.4.1 https://github.com/NOAA-EMC/NCEPLIBS-bacio.git bacio
        cd bacio && mkdir build && cd build
        cmake -DCMAKE_INSTALL_PREFIX=${bacio_ROOT} ../
        make -j2
        make install
        echo "bacio_DIR=/home/runner/bacio/lib/cmake/bacio" >> $GITHUB_ENV

#    - name: Cache SP-library v2.3.3
#      id: cache-sp-fortran
#      uses: actions/cache@v3
#      with:
#        path: /home/runner/NCEPLIBS-sp
#        key: cache-sp-fortran-${{matrix.fortran-compiler}}-key

    - name: Install SP-library v2.3.3
#      if: steps.cache-sp-fortran.outputs.cache-hit != 'true'
      run: |
        git clone --branch v2.3.3 https://github.com/NOAA-EMC/NCEPLIBS-sp.git NCEPLIBS-sp
        cd NCEPLIBS-sp && mkdir build && cd build
        cmake -DCMAKE_INSTALL_PREFIX=${sp_ROOT} ../
        make -j2
        make install
        echo "sp_DIR=/home/runner/NCEPLIBS-sp/lib/cmake/sp" >> $GITHUB_ENV

#    - name: Cache w3emc library v2.9.2
#      id: cache-w3emc-fortran
#      uses: actions/cache@v3
#      with:
#        path: /home/runner/myw3emc
#        key: cache-w3emc-fortran-${{matrix.fortran-compiler}}-key

    - name: Install w3emc library v2.9.2
#      if: steps.cache-w3emc-fortran.outputs.cache-hit != 'true'
      run: |
        git clone --branch v2.9.2 https://github.com/NOAA-EMC/NCEPLIBS-w3emc.git NCEPLIBS-w3emc
        cd NCEPLIBS-w3emc && mkdir build && cd build
        cmake -DCMAKE_INSTALL_PREFIX=${w3emc_ROOT} ../
        make -j2
        make install
        echo "w3emc_DIR=/home/runner/myw3emc/lib/cmake/w3emc" >> $GITHUB_ENV
